### ISSUE TITLE
Add Nix flake feature support 

### ISSUE THREAD

**Issue by GTrunSec** [tenzir/vast#1393]
you can find the PR here. https://github.com/GTrunSec/vast/blob/nix-flake/flake.nix

@tobim  but the   `echo -n $(git describe --tags --long --dirty) > $out` would not be passed in hydra.

nix flake build with git info : `nix build path:<path/vast>` (passing way without hydra CI)
```
copying path '/nix/store/xz5hq6y8raz288ya0lwxpz3gbaadgyra-git-2.30.0' from 'https://cache.nixos.org'...
error: "\u001b[31;1merror:\u001b[0m\u001b[34;1m --- Error --- hydra-eval-jobs\u001b[0m\na '\u001b[33;1maarch64-linux\u001b[0m' with features {\u001b[33;1m\u001b[0m} is required to build '\u001b[33;1m/nix/store/v08h0wgdsmb2x7r88f50k2i0a9pnai52-gitDescribe.out.drv\u001b[0m', but I am a '\u001b[33;1mx86_64-linux\u001b[0m' with features {\u001b[33;1mbenchmark, big-parallel, nixos-test, recursive-nix\u001b[0m}"
error: --- EndOfFile --- hydra-eval-jobs
unexpected EOF reading a line
```

flake feature commands:
- `nix build github:GTrunSec/vast/nix-flake`
- `nix run github:GTrunSec/vast/nix-flake`
-  `nix develop github:GTrunSec/vast/nix-flake`  
- 
or run native nix-build and nix-shell under repo of vast.

Second, add multi-arch CI test with Hydra:

![image](https://user-images.githubusercontent.com/21156405/108624421-ba9f8700-73f9-11eb-872e-c8c9c5579fc9.png)

WIP: rewrite vast module for deploy service on NixOS

**Comment by GTrunSec** [comment]
the Systemd of vast  based on  https://github.com/tenzir/vast/blob/master/systemd/vast.service and https://github.com/GTrunSec/simple-service-flake/blob/master/flake.nix

simple enable vast as following:

```
  services.vast = {
    enable = true;
    settings = {
      log-file = "/var/lib/vast/server.log";
       ## with custom settings 
    };
  };
```
![image](https://user-images.githubusercontent.com/21156405/108670246-6a750300-7493-11eb-932d-915f22f2c730.png)

**Comment by tobim** [comment]
That is really nice. I refrained from adding flakes support so far because the feature is not included in stable nix yet. I think it's best to wait for that release, let's hope it won't be much longer :). I'm looking forward to playing with your flake!

**Comment by GTrunSec** [comment]
Thanks for your reply. It does matter PR or Not. It just a try to integrated Zeek with vast via NixOS's module(flakes). Furthermore, I'm going to add a flake feature to the threabus. Doing incident-response(all process) in NixOps.
