### ISSUE TITLE
Display partition names consistently in log messages

### ISSUE THREAD

**Issue by lava** [tenzir/vast#1920]
With CAF 0.18, actor names must be constant strings. The active and passive partition carry their human-readable name in the variable `self->state.name` already.

In `active_partition.cpp` and `passive_partition.cpp` we currently have a lot of log messages using the actor name rather than the human-readable partition name. We need to change them like this:

```diff
  VAST_DEBUG("{} persists partition with a total size of {} bytes",
-            *self, fbchunk->size());
+            self->state.name, fbchunk->size());
```

### :100: Definition of Done

All log messages created by the active/passive partition actors use the human-readable partition name.

**Comment by dominiklohmann** [comment]
I'm closing this as stale; our experiment of using GitHub Issues has never really picked up, and our plans for this have changed since.
