### ISSUE TITLE
Extract CAF 0.17's `caf::binary_deserializer` into a standalone utility

### ISSUE THREAD

**Issue by dominiklohmann** [tenzir/vast#1921]
VAST currently serializes some data using `caf::binary_serializer`, and then deserializes it using `caf::binary_deserializer`. The serialization format changed between CAF 0.17 and 0.18, so once we upgrade to CAF 0.18 we will be unable to load some data from older databases. To this end, we need to extract the `caf::binary_deserializer` from CAF 0.17.6 into a standalone utility that does not depend on CAF at all.

The current binary serializer takes an actor system or a pointer to an execution unit as a first argument to the constructor, but that should be irrelevant for the types we currently serialize.

The interface of the new function could look something like this:

```cpp
namespace vast::detail {

/// Deserializes a contiguous byte range into an instance of type *To* in
/// the serialization format of CAF 0.17.6's binary serializer.
/// @tparam To The type to deserialize into.
/// @param from The byte range to deserialize from.
/// @returns A valid instance of *To*, or an error.
template<class To>
caf::expected<To> legacy_deserialize<T>(std::span<const std::byte> from);

} // namespace vast::detail
```

### :100: Definition of Done

- A new utility exists as a drop-in replacement for the legacy deserializer.
- The deserialization does not depend on any CAF types internally.
- The utility is tested extensively in unit tests. The following types must be tested, as they are currently written to disk in this format:
  - `vast::legacy_type`
  - `vast::qualified_record_field`
  - `vast::synopsis_ptr`
  - `vast::ids`
- We no longer use `caf::binary_deserializer` in libvast.

**Comment by 6yozo** [comment]
Commit 71d826299bab0440f3f34bb5145da9e6899dd050 implements all targeted type. Two tasks remain:
1. The 'macOS Release (Clang)' checks must pass. The 'Debian Release (GCC)' checks are successful, though.
2. Replace caf::binary_deserializer with vas::detail::legacy_deserializer.
