### ISSUE TITLE
Replace member function `memusage` with friend function `mem_usage`

### ISSUE THREAD

**Issue by mavam** [tenzir/vast#1937]
Several of our data structures have a member function `memusage` that provides an approximatation of the number of bytes the structure occupies in memory. However, this is technically an orthogonal concern to the actual API that the data structure offers. It would therefore be more natural to implement this as a free function, similar to how we treat other concepts (e.g., equality comparable).

While doing the refactoring, let's use also something that reads a bit clearer and add a `_` in there, i.e., `mem_usage(x)`.

**Comment by lava** [comment]
One thing to keep in mind is that the `memusage()` function is typically called via dynamic dispatch from the partition synopsis, so changing this to a friend function will require some addiitonal design to be able to select the right overload:

```
  for (auto& [field, synopsis] : field_synopses_)
    result += synopsis ? synopsis->memusage() : 0ull;
```

**Comment by dominiklohmann** [comment]
I'm closing this as stale; our experiment of using GitHub Issues has never really picked up, and our plans for this have changed since.
