### ISSUE TITLE
Add parsing of VLAN ID on pcap import

### ISSUE THREAD

**Issue by steveh46** [tenzir/vast#2041]
### Use Case

It is not currently possible to filter traffic for export traffic from VAST as a pcap/etc by using VLAN ID because VLAN ID is not parsed on ingestion from source pcap/traffic. 

### Feature Description

Add VLAN ID parsing on pcap ingestion

### Anything else?

Link to the original discussion on Slack : 

https://tenzir-community.slack.com/archives/C022GBMDDG8/p1641689689010700

**Comment by mavam** [comment]
Hi Steve, thanks for the feature request!

The meta data around PCAP data is currently rather thin, i.e., VAST almost doesn't do any parsing other than the connection 5-tuple. That said, VAST already decapsulates 802.1Q VLAN tags: https://github.com/tenzir/vast/blob/master/plugins/pcap/main.cpp#L157.

### Proposal

We make the *outer* and *inner* VLAN tags (both optional) available.

### Implementation

We add a `vlan` record with two fields `outer` and `inner` to the packet schema.

Thoughts?

**Comment by steveh46** [comment]
Hi again Sir, and apologies for my delay in replying 

Making both the outer and inner vlan available would be fantastic !!

**Comment by mavam** [comment]
@steveh46 please take a look at #2179. I think this implements what you want. It'd be great if you could give it a spin before we merge it!

**Comment by steveh46** [comment]
Hi Sir

Fantasic, I will take a look !!

Many Thanks,

BEst,

Steve

Steve hicks

**Comment by mavam** [comment]
@steveh46 the feature is now in master. Here are the updated docs: https://docs.tenzir.com/vast/integrations/pcap.
