### ISSUE TITLE
More friendly help UX for VAST CLI

### ISSUE THREAD

**Issue by rdettai** [tenzir/vast#2174]
### Use Case

I noticed the following behavior:
- when I run `vast -h` I get that export is a subcommand
- when I run `vast export`, the CLI tells me `!! missing_subcommand: export, usage: vast [<parameters>] <command>`. Meanwhile, the help text that is printed is the same as above, indicating again that `export` is an existing subcommand
- it is only when I run `vast export -h` that I finally understand that I need to use another subcommand like `vast export json`

### Feature Description

If this is a known issue of the current CLI framework, could we maybe use this issue to list all the possible alternatives with their pros and cons?

Meanwhile, to address the `export` usecase, could we envision a more friendly description:
`exports query results to STDOUT or file` -> `exports query results in the format specified as subcommand`

**Comment by dominiklohmann** [comment]
I'm closing this as stale; our experiment of using GitHub Issues has never really picked up, and our plans for this have changed since.
