### ISSUE TITLE
Poll the Fargate Server Task until it is ready

### ISSUE THREAD

**Issue by rdettai** [tenzir/vast#2182]
### Use Case

When starting the VAST server on Fargate (for instance with `vast-cloud start-vast-server`), the task usually takes a few minutes to be up and running. It would be useful to have a mechanism that waites for the server to be running.

### Feature Description

We should not return from the `vast-cloud start-vart-server` until the server is up and running and query-able.

**Comment by dominiklohmann** [comment]
I'm closing this as stale; our experiment of using GitHub Issues has never really picked up, and our plans for this have changed since.
