### ISSUE TITLE
Retry on failed deploy and destroy

### ISSUE THREAD

**Issue by rdettai** [tenzir/vast#2183]
### Use Case

Because of the AWS Lambda resource that is configured in the VPC, it sometimes happens that the terraform apply and destroy commands fail. It would be nice if the vast-cloud command had some retry logic to be more robust to these failures.

### Feature Description

Retry when terraform deploy/destroy fails because of the Lambda resource and apply "appropriate" wait time, but not in other failure scenarios.

**Comment by dominiklohmann** [comment]
I'm closing this as stale; our experiment of using GitHub Issues has never really picked up, and our plans for this have changed since.
