### ISSUE TITLE
Improve Cloudtrail Schema

### ISSUE THREAD

**Issue by rdettai** [tenzir/vast#2333]
### Use Case

The current Cloudtrail schema only represents partially the fields that can be present in these events. For instance `serviceEventDetails` and `insightDetails` are not parsed.

### Feature Description

- Specify the remaining fields
- As suggested by @dominiklohmann in https://github.com/tenzir/vast/pull/2322#discussion_r891488553, we might use the eventType field as selector

### Anything else?

[Official schema description](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference.html)

**Comment by dominiklohmann** [comment]
I'm closing this as stale; our experiment of using GitHub Issues has never really picked up, and our plans for this have changed since.
